/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DataRouteImport } from './routes/data'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReturnsIdRouteImport } from './routes/returns.$id'
import { Route as ReturnsNewRouteImport } from './routes/returns.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIdRoute = ReturnsIdRouteImport.update({
  id: '/returns/$id',
  path: '/returns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsNewRoute = ReturnsNewRouteImport.update({
  id: '/returns/new',
  path: '/returns/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/data': typeof DataRoute
  '/learning': typeof LearningRoute
  '/review': typeof ReviewRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/returns/new': typeof ReturnsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/data': typeof DataRoute
  '/learning': typeof LearningRoute
  '/review': typeof ReviewRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/returns/new': typeof ReturnsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/data': typeof DataRoute
  '/learning': typeof LearningRoute
  '/review': typeof ReviewRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/returns/new': typeof ReturnsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/data'
    | '/learning'
    | '/review'
    | '/returns/$id'
    | '/returns/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/data'
    | '/learning'
    | '/review'
    | '/returns/$id'
    | '/returns/new'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/data'
    | '/learning'
    | '/review'
    | '/returns/$id'
    | '/returns/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DataRoute: typeof DataRoute
  LearningRoute: typeof LearningRoute
  ReviewRoute: typeof ReviewRoute
  ReturnsIdRoute: typeof ReturnsIdRoute
  ReturnsNewRoute: typeof ReturnsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/$id': {
      id: '/returns/$id'
      path: '/returns/$id'
      fullPath: '/returns/$id'
      preLoaderRoute: typeof ReturnsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/new': {
      id: '/returns/new'
      path: '/returns/new'
      fullPath: '/returns/new'
      preLoaderRoute: typeof ReturnsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DataRoute: DataRoute,
  LearningRoute: LearningRoute,
  ReviewRoute: ReviewRoute,
  ReturnsIdRoute: ReturnsIdRoute,
  ReturnsNewRoute: ReturnsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
